### PR TITLE
SSL Support

### PR DESCRIPTION
**Pull request by hyena**
Addresses #14. I think it'll probably need some tweaks but this is far enough along that it could benefit from feedback.

The approach here involves the following:
  - mutgos_server now expects a `server.pem` file with a certificate and key
  - There is a subclass of PlainRawSocketConnection called SecureRawSocketConnection, responsible for most of the SSL logic.
  - ConnectionListener now takes in a factory method in its constructor which is expected to produce RawSocketConnections for its use. ConnectionListener is not specific to Plain or Secure RawSocketConnections now.
  - The SocketDriver is responsible for setting up the ssl context, creating the factory methods, and making two ConnectionListeners.
  - Default SSL port is 7073

Of the approach here, I think the most controversial is probably the way the factories are done in SocketDriver and the changes to the `start` logic in that class (there's probably a cleaner way - can I assume `start()` is only called once?)

The quickstart document has been updated in a very cursory way. I'll update it with more details on creating certificates after the commandline or config is more fleshed out (see #29).

This change does not include updating the docker image. That'll be a future, smaller PR.

TESTING DONE:
Connecting to both ports with and without SSL, disconnecting with handshake undone, creating and closing sockets.

### CODE REVIEW

**Comment by hyena** [comment]
As a comment, it's been probably 8 years since I've seriously done C++. I certainly hope I've used references correctly (e.g. I don't think our ssl_context will outlive the sockets using it).
But whatever I've screwed up, feel free to correct my style or approach if I'm missing something obvious here.

**Comment by nyanster** [comment]
> * mutgos_server now expects a `server.pem` file with a certificate and key

I haven't used MUTGOS before, I've just been following along via email updates, but, along with allowing for a single server.pem file, from experience with Fuzzball and the various ACME clients (particularly Certbot) it'd be useful if MUTGOS could also accept a separate privkey.pem and fullchain.pem (separate private key and certificate files).  This is because certbot outputs them in separate files: while the user can cat them into a single server.pem file, it helps Unix newbies if they don't have to.
I realise that might need to wait for a config system.

**Comment by hyena** [comment]
@nyanster Indeed. I noticed that last night. They were also `@tune`-able. Like you say though it's going to wait till we have a way to specify the files either config or commandline.

**Comment by hyena** [comment]
if `start()` is only called once and a failure to return `true` is fatal to the startup process, I may tweak how I approached this later. But that can wait till I integrate configuration with the step, which is not high urgency to me at the moment (it's important for UX, but not a blocker for development).

Thanks for the review. One question: Should we be worried about the overhead of making `get_socket()` virtual or is that over-optimizing?

**Comment by zelerin** [comment]
I finally had the time to start configuration today, and am in the midst of coding it.

For virtual vs non-virtual, I am not worried about that overhead at this time.  In most cases, it's algorithmic and data structure changes that make true performance increases.  If you need virtual or think you might need it, just use it.

**Pull request merged**
