### PR TITLE
Encrypt passwords

### PR DESCRIPTION
**Pull request by hyena**
Addresses #13 

 * Code lives under its own directory. Given that this is a codebase with a different lineage (e.g. not written by you) and from a different, existing library, I wanted it isolated despite its simplicity: https://github.com/trusch/libbcrypt Its license is MIT so I think this is alright.

 * bcrypt is configurable with a 'work factor' parameter controlling how long it takes to run. 10 is what most implementations use. The library I stripped down uses 12 by default. Increasing the factor by one reliably doubles the calculation time.

  I tested the speed with some code like the following:
```
#include <iostream>
#include <chrono>

#include "bcrypt/BCrypt.hpp"

// 12 is the default value in the library. 10 is what most implementations use.
int rounds = 12;
auto t1 = std::chrono::high_resolution_clock::now();
auto pass = BCrypt::generateHash("xyzzy", rounds);
auto t2 = std::chrono::high_resolution_clock::now();
auto right = BCrypt::validatePassword("xyzzy", pass);
auto t3 = std::chrono::high_resolution_clock::now();
std::cout << "password " << pass << " took "
          << std::chrono::duration_cast<std::chrono::milliseconds>(t2-t1).count()
          << " milliseconds\n"
          << "And " << std::chrono::duration_cast<std::chrono::milliseconds>(t3-t2).count()
          << " to verify with " << rounds << " rounds\n";
```

  On my machine, I found that a value of 10 was about 300ms and a value of 12 was about 1200ms as expected.

  I've set it to 10 for now even though that's less than half a second because as written we're calculating it while we hold a writer lock to the player (I can easily code up a way around this) and I don't know if this is on the critical path (don't have a good solution to that). It's a constant right now but we can tweak it.

  Note that even if we change the 'workload' values while the server is running, the code will still work: Passwords are saved with the workload in them so they can still be checked.

 * The naming convention's been broken somewhat (#include "bcrypt/BCrypt.hpp"). I went back and forth on changing this a few times. Eventually I kept the style of the original library here to help it stand out as an external library we pulled in.

 * The dump files still contain unencrypted passwords. If we intend this format to be used for something more serious than just providing a basic testing database (e.g. if we want to support it as an export format), this isn't too hard to fix.

 * You'll need to regenerate your db or manually update encrypted_password fields through sqlite to test this. Tested by logging in with correct password.

### CODE REVIEW

**Comment by hyena** [comment]
If you balk at the size of this import, I have a slimmer solution too: We can do SHA-256 hashing with `crypt()` on Linux the same way most modern distros do their `/etc/shadow` files. Only tricky bit is reading sufficient salt bytes from `/dev/urandom`

**Comment by zelerin** [comment]
A few things, one of which needs changing before I merge (or can be debated!)...

I don't think it's a big deal to lock Player while the password is being validated - this is assuming a READ lock is acquired, and not a write lock (which should already be the case).  Setting the password would have a write lock, of course.  The same Player is not logging in many times a minute, so I don't think anyone's going to notice a slowdown.  The only downside is the whole comm thread is locked up while the validation is taking place.  We can always throttle logins in the future if this becomes an actual problem, but I suspect it won't be noticeable since logins are a relatively infrequent event.  In other words, this can be tuned for performance at a later time if it becomes a problem.  I agree work factor 10 is the highest we can go, given the time required to encrypt.

For bcrypt itself, no need to change file names or any of its formatting, etc. It should be provided in exactly (or close to) the same form as you downloaded it.  The only issue here is I'm realizing the list of directories is getting pretty big and may be due for a reorganization!  Could you make a subdirectory that would contain products like this?  I'm not sure what to call it (suggestions?).  dependencies?  external?  Your idea here!  I suspect the JSON parser will soon join it, and AngelScript as well at some point (it was designed to be embedded).  For instance, under angelscriptinterface, I have an 'add_ons' directory which contains any of the optional add ons I'm using from AngelScript - they don't automatically get compiled with the base product and have to be embedded.

Dump files are currently fine to remain unencrypted; they are what new installs use to bootstrap the DB; they are expected to change passwords upon first login anyway.  If we decide to use a similar format for exporting (which is an eventual feature I want - 100% site portability to another server), we can add the ability to manually get and set the encrypted password at that time.

Too much text, I know. In summary, these are the things I think need to be done before I can merge:
  * Create a new top-level directory to house external open source products so they are easily identified as being external and collected in basically one place.  Put bcrypt in there.  If you made the C++ interface yourself, you are welcome to put that little section somewhere else, like 'utilities' (not mandatory).
  * Delete the #include <iostream>  out of Player since it is no longer doing couts.

**Comment by hyena** [comment]
A lot of my changes to the layout of the library were there to make it conform closer to the style of its sibling components, but if such external libraries can live in a top level directory of their own that concern goes away. As for what to name it, either `lib` or `third_party` probably. The latter is less confusing. Thoughts?

The only question I have here is how much to tweak/change their CMakeLists.txt. Should we try to keep the compilation options consistent? A `make clean` needs to do the right thing for the whole repo.

Incidentally, git submodules might seem like a good solution to this, but they're more trouble than they're worth. We should just check in code directly imo.

**Comment by zelerin** [comment]
third_party works.  I envisioned it sort of like this (it looks like I was unclear earlier):
src/third_party/bcrypt

Does that make more sense?  In other words, still within our source tree for easy building, but slightly separate so there's no doubt we've imported it from elsewhere.  It's easy to do the CMake part that way, so no concerns about clean, etc.

**Comment by hyena** [comment]
@zelerin Updated. Look at the `third_party` directory and the `README.md` inside. The basic approach is to add in libraries and modify their CMakeLists.txt to make it play nicely with mutgos.

I tried and rejected a few other approaches (e.g. making a third_party/include and third_party/lib directory and trying to use `external_process()` to install into them) but rejected these as too fiddly. They're doable, however. The cost of not doing this is that the top-level CMakeLists.txt now needs to have more `include_directories()` entries.

Testing done: Compiled and ran it.

**Comment by zelerin** [comment]
Looks good!  Thanks for making the changes!  I'll go ahead and merge it.  I have a some concerns about the intel-only assembler portion, since that means it won't run on ARM VPSs, for instance.  Admittedly,  this is not a big concern right now and I think revisiting it potentially much later is fine.  As you noted, there may be issues when we have an installer, but given MUTGOS is a specialty application, I was planning for it to be installed in its own separate area to avoid conflicts.

It's possible some of this stuff may be changed later, but I'd rather take the changes now and have a good base.  Thanks for your help!

**Comment by zelerin** [comment]
Looking slightly closer, though I'm not 100% positive, it looks like the assembler gets turned off on other platforms and a slightly less efficient (but universal) method is used instead.  So it may not be that bad after all.

**Comment by hyena** [comment]
Yes. In my previous version I had pre-emptively removed the assembly file and it still worked. So if there are problems we can always repeat that.

Be sure to take a look at third_party/README.md to make sure that format will work for what you plan with angelscript.

**Comment by zelerin** [comment]
The readme looks good to me!  Nice and simple.

**Pull request merged**
